### ISSUE TITLE
Problems getting it to work

### ISSUE THREAD

**Issue by CoalaJoe** [GerogeChong/spine-sdl#1]
Hey there. Was looking into spine and SDL2.

I finally got it to compile (replacing GLES with GL headers in spine-sdl.cpp and spine-sdl.h) and am now facing the following.
```
Fehler: »YOUR_OWN_SDL_Renderer« wurde in diesem Gültigkeitsbereich nicht definiert
     SDL_Texture* texture=SDL_CreateTextureFromSurface(YOUR_OWN_SDL_Renderer, img);
```

I'd guess that I have to inject my instanciated renderer from here:
```
SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
```

There are also a lot of file referenced that simply do not exists. Almost everything in src/render/SDL_render.c and SDL_sysrender.h

I hope you can help me out.

**Comment by GerogeChong** [comment]
Hi,there,sorry to check this issue late:
As I said in "SETUP", You have to do the following steps (a) and (b) properly:(Which I guess u didn't do)

(a) Copy SDL/src/include/SDL_opengles.h and SDL/src/include/SDL_render.h,then paste them to your projects' SDL src/include directory. (which replaced the same named files)

(b) Just like we did in (a) , copy all the files in SDL/src/render (SDL_render.c,SDL_sysrender.h,and files in "opengles" directory) and then replace the same named files in your projects' SDL src/render direcotry with them.

these files are modified a lot by me comparing to the official SDL2 files.(Mainly added SDL_RenderCopySpine)

**Comment by CoalaJoe** [comment]
Hey there.
Thank you for your reply. I changed from SDL2 to SFML2. I will check this out later though.
